In [ ]:
import numpy as np
import scipy

from PIL import Image, ImageFilter  # imports the library

#import matplotlib
#import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors  import NearestCentroid
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC


Xtrain=np.zeros((1575,196608))
Ytrain=np.zeros((1575,1))
J=0

for i in range(0,75):
    if i<10:
        agriculturalfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\agricultural\agricultural0' + str(i) + '.tif'
        airplanefname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\airplane\airplane0' + str(i) + '.tif'
        baseballdiamondfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\baseballdiamond\baseballdiamond0' + str(i) + '.tif'
        beachfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\beach\beach0' + str(i) + '.tif'
        buildingsfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\buildings\buildings0' + str(i) + '.tif'
        chaparralfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\chaparral\chaparral0' + str(i) + '.tif'
        denseresidentialfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\denseresidential\denseresidential0' + str(i) + '.tif'
        forestfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\forest\forest0' + str(i) + '.tif'
        freewayfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\freeway\freeway0' + str(i) + '.tif'
        golfcoursefname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\golfcourse\golfcourse0' + str(i) + '.tif'
        harborfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\harbor\harbor0' + str(i) + '.tif'
        intersectionfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\intersection\intersection0' + str(i) + '.tif'
        mediumresidentialfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\mediumresidential\mediumresidential0' + str(i) + '.tif'
        mobilehomeparkfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\mobilehomepark\mobilehomepark0' + str(i) + '.tif'
        overpassfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\overpass\overpass0' + str(i) + '.tif'
        parkinglotfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\parkinglot\parkinglot0' + str(i) + '.tif'
        riverfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\river\river0' + str(i) + '.tif'
        runwayfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\runway\runway0' + str(i) + '.tif'
        sparseresidentialfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\sparseresidential\sparseresidential0' + str(i) + '.tif'
        storagetanksfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\storagetanks\storagetanks0' + str(i) + '.tif'
        tenniscourtfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\tenniscourt\tenniscourt0' + str(i) + '.tif'
    else:
        agriculturalfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\agricultural\agricultural' + str(i) + '.tif'
        airplanefname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\airplane\airplane' + str(i) + '.tif'
        baseballdiamondfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\baseballdiamond\baseballdiamond' + str(i) + '.tif'
        beachfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\beach\beach' + str(i) + '.tif'
        buildingsfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\buildings\buildings' + str(i) + '.tif'
        chaparralfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\chaparral\chaparral' + str(i) + '.tif'
        denseresidentialfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\denseresidential\denseresidential' + str(i) + '.tif'
        forestfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\forest\forest' + str(i) + '.tif'
        freewayfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\freeway\freeway' + str(i) + '.tif'
        golfcoursefname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\golfcourse\golfcourse' + str(i) + '.tif'
        harborfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\harbor\harbor' + str(i) + '.tif'
        intersectionfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\intersection\intersection' + str(i) + '.tif'
        mediumresidentialfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\mediumresidential\mediumresidential' + str(i) + '.tif'
        mobilehomeparkfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\mobilehomepark\mobilehomepark' + str(i) + '.tif'
        overpassfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\overpass\overpass' + str(i) + '.tif'
        parkinglotfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\parkinglot\parkinglot' + str(i) + '.tif'
        riverfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\river\river' + str(i) + '.tif'
        runwayfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\runway\runway' + str(i) + '.tif'
        sparseresidentialfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\sparseresidential\sparseresidential' + str(i) + '.tif'
        storagetanksfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\storagetanks\storagetanks' + str(i) + '.tif'
        tenniscourtfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\tenniscourt\tenniscourt' + str(i) + '.tif'

    Aagricultural = Image.open(agriculturalfname)  # 256x256x3 Input Images of Digits
    Aagricultural = Aagricultural.resize((256,256))
    Xtrain[J,:] = np.transpose(np.asarray(Aagricultural).reshape(196608,1))
        
    Aairplane = Image.open(airplanefname)  # 256x256x3 Input Images of Digits
    Aairplane = Aairplane.resize((256,256))
    Xtrain[J+1,:] = np.transpose(np.array(Aairplane).reshape(196608,1))
    
    Abaseballdiamond = Image.open(baseballdiamondfname)  # 256x256x3 Input Images of Digits
    Abaseballdiamond = Abaseballdiamond.resize((256,256))
    Xtrain[J+2,:] = np.transpose(np.array(Abaseballdiamond).reshape(196608,1))
    
    Abeach = Image.open(beachfname)  # 256x256x3 Input Images of Digits
    Abeach = Abeach.resize((256,256))
    Xtrain[J+3,:] = np.transpose(np.array(Abeach).reshape(196608,1))
    
    Abuildings = Image.open(buildingsfname)  # 256x256x3 Input Images of Digits
    Abuildings = Abuildings.resize((256,256))
    Xtrain[J+4,:] = np.transpose(np.array(Abuildings).reshape(196608,1))
    
    Achaparral = Image.open(chaparralfname)  # 256x256x3 Input Images of Digits
    Achaparral = Achaparral.resize((256,256))
    Xtrain[J+5,:] = np.transpose(np.array(Achaparral).reshape(196608,1))
    
    Adenseresidential = Image.open(denseresidentialfname)  # 256x256x3 Input Images of Digits
    Adenseresidential = Adenseresidential.resize((256,256))
    Xtrain[J+6,:] = np.transpose(np.array(Adenseresidential).reshape(196608,1))
    
    Aforest = Image.open(forestfname)  # 256x256x3 Input Images of Digits
    Aforest = Aforest.resize((256,256))
    Xtrain[J+7,:] = np.transpose(np.array(Aforest).reshape(196608,1))
    
    Afreeway = Image.open(freewayfname)  # 256x256x3 Input Images of Digits
    Afreeway = Afreeway.resize((256,256))
    Xtrain[J+8,:] = np.transpose(np.array(Afreeway).reshape(196608,1))
    
    Agolfcourse = Image.open(golfcoursefname)  # 256x256x3 Input Images of Digits
    Agolfcourse = Agolfcourse.resize((256,256))
    Xtrain[J+9,:] = np.transpose(np.array(Agolfcourse).reshape(196608,1))
    
    Aharbor = Image.open(harborfname)  # 256x256x3 Input Images of Digits
    Aharbor = Aharbor.resize((256,256))
    Xtrain[J+10,:] = np.transpose(np.array(Aharbor).reshape(196608,1))
    
    Aintersection = Image.open(intersectionfname)  # 256x256x3 Input Images of Digits
    Aintersection = Aintersection.resize((256,256))
    Xtrain[J+11,:] = np.transpose(np.array(Aintersection).reshape(196608,1))
    
    Amediumresidential = Image.open(mediumresidentialfname)  # 256x256x3 Input Images of Digits
    Amediumresidential = Amediumresidential.resize((256,256))
    Xtrain[J+12,:] = np.transpose(np.array(Amediumresidential).reshape(196608,1))
    
    Amobilehomepark = Image.open(mobilehomeparkfname)  # 256x256x3 Input Images of Digits
    Amobilehomepark = Amobilehomepark.resize((256,256))
    Xtrain[J+13,:] = np.transpose(np.array(Amobilehomepark).reshape(196608,1))
    
    Aoverpass = Image.open(overpassfname)  # 256x256x3 Input Images of Digits
    Aoverpass = Aoverpass.resize((256,256))
    Xtrain[J+14,:] = np.transpose(np.array(Aoverpass).reshape(196608,1))
    
    Aparkinglot = Image.open(parkinglotfname)  # 256x256x3 Input Images of Digits
    Aparkinglot = Aparkinglot.resize((256,256))
    Xtrain[J+15,:] = np.transpose(np.array(Aparkinglot).reshape(196608,1))
    
    Ariver = Image.open(riverfname)  # 256x256x3 Input Images of Digits
    Ariver = Ariver.resize((256,256))
    Xtrain[J+16,:] = np.transpose(np.array(Ariver).reshape(196608,1))
    
    Arunway = Image.open(runwayfname)  # 256x256x3 Input Images of Digits
    Arunway = Arunway.resize((256,256))
    Xtrain[J+17,:] = np.transpose(np.array(Arunway).reshape(196608,1))
    
    Asparseresidential = Image.open(sparseresidentialfname)  # 256x256x3 Input Images of Digits
    Asparseresidential = Asparseresidential.resize((256,256))
    Xtrain[J+18,:] = np.transpose(np.array(Asparseresidential).reshape(196608,1))
    
    Astoragetanks = Image.open(storagetanksfname)  # 256x256x3 Input Images of Digits
    Astoragetanks = Astoragetanks.resize((256,256))
    Xtrain[J+19,:] = np.transpose(np.array(Astoragetanks).reshape(196608,1))
    
    Atenniscourt = Image.open(tenniscourtfname)  # 256x256x3 Input Images of Digits
    Atenniscourt = Atenniscourt.resize((256,256))
    Xtrain[J+20,:] = np.transpose(np.array(Atenniscourt).reshape(196608,1))
    
    Ytrain[J] = 1
    Ytrain[J+1] = 2
    Ytrain[J+2] = 3
    Ytrain[J+3] = 4
    Ytrain[J+4] = 5
    Ytrain[J+5] = 6
    Ytrain[J+6] = 7
    Ytrain[J+7] = 8
    Ytrain[J+8] = 9
    Ytrain[J+9] = 10
    Ytrain[J+10] = 11
    Ytrain[J+11] = 12
    Ytrain[J+12] = 13
    Ytrain[J+13] = 14
    Ytrain[J+14] = 15
    Ytrain[J+15] = 16
    Ytrain[J+16] = 17
    Ytrain[J+17] = 18
    Ytrain[J+18] = 19
    Ytrain[J+19] = 20                        
    Ytrain[J+20] = 21
    J = J + 21


Xtest=np.zeros((525,196608))
Ytest=np.zeros((525,1))
J = 0
                           
for i in range(75,100):
    agriculturalfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\agricultural\agricultural' + str(i) + '.tif'
    airplanefname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\airplane\airplane' + str(i) + '.tif'
    baseballdiamondfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\baseballdiamond\baseballdiamond' + str(i) + '.tif'
    beachfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\beach\beach' + str(i) + '.tif'
    buildingsfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\buildings\buildings' + str(i) + '.tif'
    chaparralfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\chaparral\chaparral' + str(i) + '.tif'
    denseresidentialfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\denseresidential\denseresidential' + str(i) + '.tif'
    forestfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\forest\forest' + str(i) + '.tif'
    freewayfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\freeway\freeway' + str(i) + '.tif'
    golfcoursefname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\golfcourse\golfcourse' + str(i) + '.tif'
    harborfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\harbor\harbor' + str(i) + '.tif'
    intersectionfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\intersection\intersection' + str(i) + '.tif'
    mediumresidentialfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\mediumresidential\mediumresidential' + str(i) + '.tif'
    mobilehomeparkfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\mobilehomepark\mobilehomepark' + str(i) + '.tif'
    overpassfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\overpass\overpass' + str(i) + '.tif'
    parkinglotfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\parkinglot\parkinglot' + str(i) + '.tif'
    riverfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\river\river' + str(i) + '.tif'
    runwayfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\runway\runway' + str(i) + '.tif'
    sparseresidentialfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\sparseresidential\sparseresidential' + str(i) + '.tif'
    storagetanksfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\storagetanks\storagetanks' + str(i) + '.tif'
    tenniscourtfname = r'D:\Mine\PhD\Database\UCMerced_LandUse\UCMerced_LandUse\Images\tenniscourt\tenniscourt' + str(i) + '.tif'
    
    Aagricultural = Image.open(agriculturalfname)  # 256x256x3 Input Images of Digits
    Aagricultural = Aagricultural.resize((256,256))
    Xtest[J,:] = np.transpose(np.asarray(Aagricultural).reshape(196608,1))
        
    Aairplane = Image.open(airplanefname)  # 256x256x3 Input Images of Digits
    Aairplane = Aairplane.resize((256,256))
    Xtest[J+1,:] = np.transpose(np.array(Aairplane).reshape(196608,1))
    
    Abaseballdiamond = Image.open(baseballdiamondfname)  # 256x256x3 Input Images of Digits
    Abaseballdiamond = Abaseballdiamond.resize((256,256))
    Xtest[J+2,:] = np.transpose(np.array(Abaseballdiamond).reshape(196608,1))
    
    Abeach = Image.open(beachfname)  # 256x256x3 Input Images of Digits
    Abeach = Abeach.resize((256,256))
    Xtest[J+3,:] = np.transpose(np.array(Abeach).reshape(196608,1))
    
    Abuildings = Image.open(buildingsfname)  # 256x256x3 Input Images of Digits
    Abuildings = Abuildings.resize((256,256))
    Xtest[J+4,:] = np.transpose(np.array(Abuildings).reshape(196608,1))
    
    Achaparral = Image.open(chaparralfname)  # 256x256x3 Input Images of Digits
    Achaparral = Achaparral.resize((256,256))
    Xtest[J+5,:] = np.transpose(np.array(Achaparral).reshape(196608,1))
    
    Adenseresidential = Image.open(denseresidentialfname)  # 256x256x3 Input Images of Digits
    Adenseresidential = Adenseresidential.resize((256,256))
    Xtest[J+6,:] = np.transpose(np.array(Adenseresidential).reshape(196608,1))
    
    Aforest = Image.open(forestfname)  # 256x256x3 Input Images of Digits
    Aforest = Aforest.resize((256,256))
    Xtest[J+7,:] = np.transpose(np.array(Aforest).reshape(196608,1))
    
    Afreeway = Image.open(freewayfname)  # 256x256x3 Input Images of Digits
    Afreeway = Afreeway.resize((256,256))
    Xtest[J+8,:] = np.transpose(np.array(Afreeway).reshape(196608,1))
    
    Agolfcourse = Image.open(golfcoursefname)  # 256x256x3 Input Images of Digits
    Agolfcourse = Agolfcourse.resize((256,256))
    Xtest[J+9,:] = np.transpose(np.array(Agolfcourse).reshape(196608,1))
    
    Aharbor = Image.open(harborfname)  # 256x256x3 Input Images of Digits
    Aharbor = Aharbor.resize((256,256))
    Xtest[J+10,:] = np.transpose(np.array(Aharbor).reshape(196608,1))
    
    Aintersection = Image.open(intersectionfname)  # 256x256x3 Input Images of Digits
    Aintersection = Aintersection.resize((256,256))
    Xtest[J+11,:] = np.transpose(np.array(Aintersection).reshape(196608,1))
    
    Amediumresidential = Image.open(mediumresidentialfname)  # 256x256x3 Input Images of Digits
    Amediumresidential = Amediumresidential.resize((256,256))
    Xtest[J+12,:] = np.transpose(np.array(Amediumresidential).reshape(196608,1))
    
    Amobilehomepark = Image.open(mobilehomeparkfname)  # 256x256x3 Input Images of Digits
    Amobilehomepark = Amobilehomepark.resize((256,256))
    Xtest[J+13,:] = np.transpose(np.array(Amobilehomepark).reshape(196608,1))
    
    Aoverpass = Image.open(overpassfname)  # 256x256x3 Input Images of Digits
    Aoverpass = Aoverpass.resize((256,256))
    Xtest[J+14,:] = np.transpose(np.array(Aoverpass).reshape(196608,1))
    
    Aparkinglot = Image.open(parkinglotfname)  # 256x256x3 Input Images of Digits
    Aparkinglot = Aparkinglot.resize((256,256))
    Xtest[J+15,:] = np.transpose(np.array(Aparkinglot).reshape(196608,1))
    
    Ariver = Image.open(riverfname)  # 256x256x3 Input Images of Digits
    Ariver = Ariver.resize((256,256))
    Xtest[J+16,:] = np.transpose(np.array(Ariver).reshape(196608,1))
    
    Arunway = Image.open(runwayfname)  # 256x256x3 Input Images of Digits
    Arunway = Arunway.resize((256,256))
    Xtest[J+17,:] = np.transpose(np.array(Arunway).reshape(196608,1))
    
    Asparseresidential = Image.open(sparseresidentialfname)  # 256x256x3 Input Images of Digits
    Asparseresidential = Asparseresidential.resize((256,256))
    Xtest[J+18,:] = np.transpose(np.array(Asparseresidential).reshape(196608,1))
    
    Astoragetanks = Image.open(storagetanksfname)  # 256x256x3 Input Images of Digits
    Astoragetanks = Astoragetanks.resize((256,256))
    Xtest[J+19,:] = np.transpose(np.array(Astoragetanks).reshape(196608,1))
    
    Atenniscourt = Image.open(tenniscourtfname)  # 256x256x3 Input Images of Digits
    Atenniscourt = Atenniscourt.resize((256,256))
    Xtest[J+20,:] = np.transpose(np.array(Atenniscourt).reshape(196608,1))
    
    Ytest[J] = 1
    Ytest[J+1] = 2
    Ytest[J+2] = 3
    Ytest[J+3] = 4
    Ytest[J+4] = 5
    Ytest[J+5] = 6
    Ytest[J+6] = 7
    Ytest[J+7] = 8
    Ytest[J+8] = 9
    Ytest[J+9] = 10
    Ytest[J+10] = 11
    Ytest[J+11] = 12
    Ytest[J+12] = 13
    Ytest[J+13] = 14
    Ytest[J+14] = 15
    Ytest[J+15] = 16
    Ytest[J+16] = 17
    Ytest[J+17] = 18
    Ytest[J+18] = 19
    Ytest[J+19] = 20                        
    Ytest[J+20] = 21
    J = J + 21

modelDT = DecisionTreeClassifier(random_state=0)
modelDT.fit(Xtrain, Ytrain)

predictionsDTR = modelDT.predict(Xtrain)

print(accuracy_score(Ytrain, predictionsDTR))
print(confusion_matrix(Ytrain, predictionsDTR))
print(classification_report(Ytrain, predictionsDTR))

predictionsDTS = modelDT.predict(Xtest)

print(accuracy_score(Ytest, predictionsDTS))
print(confusion_matrix(Ytest, predictionsDTS))
print(classification_report(Ytest, predictionsDTS))
    
    
modelNC = NearestCentroid()
modelNC.fit(Xtrain, Ytrain)

predictionsNCR = modelNC.predict(Xtrain)

print(accuracy_score(Ytrain, predictionsNCR))
print(confusion_matrix(Ytrain, predictionsNCR))
print(classification_report(Ytrain, predictionsNCR))

predictionsNCS = modelNC.predict(Xtest)

print(accuracy_score(Ytest, predictionsNCS))
print(confusion_matrix(Ytest, predictionsNCS))
print(classification_report(Ytest, predictionsNCS))    


modelSVM = SVC(kernel='rbf')
modelSVM.fit(Xtrain, Ytrain)

predictionsSVMR = modelSVM.predict(Xtrain)

print(accuracy_score(Ytrain, predictionsSVMR))
print(confusion_matrix(Ytrain, predictionsSVMR))
print(classification_report(Ytrain, predictionsSVMR))

predictionsSVMS = modelSVM.predict(Xtest)

print(accuracy_score(Ytest, predictionsSVMS))
print(confusion_matrix(Ytest, predictionsSVMS))
print(classification_report(Ytest, predictionsSVMS))

modelNN = MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(500,), random_state=1)
modelNN.fit(Xtrain, Ytrain)

predictionsNNR = modelNN.predict(Xtrain)

print(accuracy_score(Ytrain, predictionsNNR))
print(confusion_matrix(Ytrain, predictionsNNR))
print(classification_report(Ytrain, predictionsNNR))

predictionsNNS = modelNN.predict(Xtest)

print(accuracy_score(Ytest, predictionsNNS))
print(confusion_matrix(Ytest, predictionsNNS))
print(classification_report(Ytest, predictionsNNS))

1.0
[[75  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 75  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 75  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 75  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 75  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 75  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 75  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 75  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 75  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 75  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 75  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 75  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 75  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 75  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 75  0  0  0  0  0  0]
 [ 0  

C:\Users\Khalid\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.32
[[11 15  0 11  0  0  0  5  0  0  1  3  0  2  0  7  5  0  0  2 13]
 [ 2 22  3 20  5  0  1  5  4  0  0  1  0  1  0  1  4  0  2  1  3]
 [ 5  8  9 12  2  1  1 22  2  5  0  0  1  0  0  0  2  0  0  3  2]
 [ 2  2  0 60  0  0  0  0  1  0  0  0  0  6  0  0  1  0  0  1  2]
 [ 0  4  1 13 26  0  4  1  2  0  1  1  3  0  1  0  3  5  2  4  4]
 [ 0  3  0  1  0 63  0  0  0  0  0  1  0  0  0  1  4  0  0  0  2]
 [ 1  6  2  1  3  7 21  4  0  1  3  1  1  0  2  1  9  1  0  3  8]
 [ 0  1  0  0  0  0  0 51  0  0  0  3  0  3  0  2  9  0  0  2  4]
 [ 2  5  3 12  1  3  4  1 21  0  0  1  0  4  2  0  2  0  5  5  4]
 [ 4 16  7  5  3  0  0  2  1 11  1  1  2  0  0  2  2  1  4  7  6]
 [ 1  5  0  0  4  0  1 12  0  1 31  2  5  3  2  0  2  2  0  0  4]
 [ 0  8  3  3  2  2  0  1  2  1  1 13  3  1  1  2 16  0  2  7  7]
 [ 3 11  1  1  2  9  2  0  1  0  3  3 17  3  0  3  8  0  3  1  4]
 [ 0  5  1  3  2  6  1  0  0  0  6  1  0 29  0  4  5  1  1  6  4]
 [ 1  4  0 12  2  1  0 17  7  0  0  1  0  1 16  0  2  0  3  4  4]
 [ 1 

C:\Users\Khalid\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


1.0
[[75  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 75  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 75  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 75  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 75  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 75  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 75  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 75  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 75  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 75  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 75  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 75  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 75  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 75  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 75  0  0  0  0  0  0]
 [ 0  

C:\Users\Khalid\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

         1.0       0.00      0.00      0.00        25
         2.0       0.00      0.00      0.00        25
         3.0       0.00      0.00      0.00        25
         4.0       0.00      0.00      0.00        25
         5.0       0.00      0.00      0.00        25
         6.0       0.00      0.00      0.00        25
         7.0       0.00      0.00      0.00        25
         8.0       0.00      0.00      0.00        25
         9.0       0.00      0.00      0.00        25
        10.0       0.00      0.00      0.00        25
        11.0       0.00      0.00      0.00        25
        12.0       0.00      0.00      0.00        25
        13.0       0.00      0.00      0.00        25
        14.0       0.00      0.00      0.00        25
        15.0       0.00      0.00      0.00        25
        16.0       0.00      0.00      0.00        25
        17.0       0.00      0.00      0.00        25
        18.0       0.00    

C:\Users\Khalid\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
